### ISSUE TITLE
Support for azure pipelines

### ISSUE THREAD

**Issue by lorenzwalthert** [ropensci/tic#169]
Do we merely need to translate the [azure-pipelines.yml](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example)? I am trying to make it work.

**Comment by lorenzwalthert** [comment]
I think I finally figured out one way. Main problem: You must use a private library because of permissions. Second problem: You can't `chmod 777` as suggested [here](https://github.com/rocker-org/rocker-versioned/issues/108#issuecomment-435055806) because you don't have the permissions. Also, you can't use `sudo` anyways because the command simply does not exist: https://github.com/MicrosoftDocs/vsts-docs/issues/2939. Anyways, I thought I could set up a private library by first creating a new folder and then point to it with the ENV variable `R_LIB_SITE`. Turns out this will not add the new lib loc at the beginning of the path but at the end, so installation still fails. Using `R_LIB_USER` does not work because it will be overwritten by the system, most likely when R is started. Remains to set the lib paths explicitly in .Rprofile. At some point, I also thought we need to tell bash explicitly to use the profiles (i.e. disable `--no-profile`, which is a flag that is *set by default*, https://github.com/Microsoft/azure-pipelines-tasks/issues/8259) but since I chose the `.Rprofile` approach later, it was probably irrelevant. So a WIP looks like this:

```yaml
pool:
  vmImage: 'ubuntu-16.04'

container:
  image: 'rocker/tidyverse:latest'


variables:
  _R_CHECK_FORCE_SUGGESTS_: false
  MAKEFLAGS: "-j 2"

steps:
- bash: R -q -e 'writeLines(".libPaths(\"~/R-private\")", ".Rprofile"); dir.create("~/R-private", recursive = TRUE)'
  displayName: "preliminaries"
- bash: R -q -e 'install.packages(c("remotes", "curl", "knitr", "rmarkdown")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); remotes::install_deps(dependencies = TRUE); tic::before_install()'
  displayName: 'before_install'
- bash: R -q -e 'tic::install()'
  displayName: 'install'
- bash: R -q -e 'tic::after_install()'
  displayName: 'after_install'
- bash: R -q -e 'tic::before_script()'
  displayName: 'before_script'
- bash: R -q -e 'tic::script()'
  displayName: 'script'
- bash: R -q -e 'tic::after_success()'
  displayName: 'after_success'
```

Which has not yet implemented the step for `after_failure`.
